### PR TITLE
fix: stat github wiki remotes to verify their existence

### PR DESCRIPTION
**Pull request by mtoohey31**
As far as I can tell, the `HasPages` property for GitHub repositories doesn't indicate whether their wiki contains pages, it indicates whether [GitHub Pages](https://pages.github.com/) is enabled (though it's difficult to tell because I can't find documentation anywhere). I can't find any way to check whether the wiki is populated via the API. This fix verifies that the wiki exists by attempting to connect to it and listing the available refs. This does have a performance impact since (as #78 metions) wikis are enabled by default, so we have to attempt to list refs in almost all wikis, it doesn't take too long though. The auth code is copied from the local module's `cloneRepository` function.

We may be able to do the same thing for Gitea if this is an acceptable solution.

### CODE REVIEW

**Comment by mtoohey31** [comment]
Great! Would you still like it to be in a different step of the process, or is this OK as is? My thought processes was that we should do it in this step because we only want to run this test for GitHub wikis, and it would be more complicated to check whether something is a GitHub wiki, a wiki from another provider, or simply a repo ending in `.wiki` further on.

**Comment by cooperspencer** [comment]
It is fine where it is. One thing that I just thought of is, that we can put this check in a separate module as a function and just call it for the other code hoster too. It would fit in the local or types module

**Comment by mtoohey31** [comment]
Ok, I've moved the check into a function in the types package, and added checks to gitea as well. Like I mentioned in #89 though, my gitea setup is kind of irregular so it would be great if you could test whether the changes for gitea work.

**Review by cooperspencer — APPROVED** [review]

**Comment by cooperspencer** [comment]
I ran it against my gitea instance and it worked fine. Thank you for the contribution

**Pull request merged**
