### PR TITLE
feat: backup starred repos

### PR DESCRIPTION
**Pull request by mtoohey31**
This pull request adds support for including users' starred repos in backups from github, gitea, and gitlab. Bitbucket support isn't included because it doesn't appear to have any equivalent feature, and gogs isn't supported because its API doesn't seem to support fetching a user's stars (though if [gogs/2198](https://github.com/gogs/gogs/issues/2198) is ever closed, this may be resolved in the process).

## Testing

- [x] github
- [x] gitea
- [x] gitlab

### CODE REVIEW

**Comment by cooperspencer** [comment]
that is a nice functionality, thanks for that :smile:

**Comment by mtoohey31** [comment]
Thanks, I'm glad you think so!

I've finished testing with gitlab; the original implementation wasn't correct, but it's fixed now. It seems like the first page of results was being pulled twice though, so I made some changes in 4c1c7a05bae184f6ede0023e7c014e3a06619268. It would be great if you could double check that commit to make sure I haven't misunderstood how it's supposed to work.

Finally, if you're able to, I would really appreciate it if you could do the gitea testing. My local gitea instance doesn't have the ssh port exposed, and I couldn't figure out how to make it work with a token instead...

Also, thanks for making this project, it's a much better solution than my current backup method :smile:

**Comment by cooperspencer** [comment]
Sure, I'll test it tomorrow and merge it afterwards.

**Comment by mtoohey31** [comment]
Great, thanks!

**Comment by cooperspencer** [comment]
Works great. Thanks a lot for this awesome contribution :smile:

**Pull request merged**
